routes:
  - uri: /users/*
    plugins:
      cors:
        allow_origins: "http://localhost:3000"
        allow_methods: "GET,POST,PUT,DELETE"
    upstream:
      nodes:
        "userservice:8080": 1
      type: roundrobin

  - uri: /orders/*
    plugins:
      cors:
        allow_origins: "http://localhost:3000"
        allow_methods: "GET,POST,PUT,DELETE"
    upstream:
      nodes:
        "orderservice:8080": 1
      type: roundrobin
#END