version: '3.10'
services:
  apisix:
    image: apache/apisix:latest
    container_name: apisix
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    volumes:
      - ./config.yaml:/usr/local/apisix/conf/apisix.yaml
    networks:
      apisix_network:
    environment:
      - APISIX_STAND_ALONE=true 

  userservice:
    build:
      context: ./user-service/UserService
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "8001:8080"
    networks:
      apisix_network:

  orderservice:
    build:
      context: ./order-service/OrderService
      dockerfile: Dockerfile
    container_name: orderservice
    ports:
      - "8002:8080"
    networks:
      apisix_network:

  frontend:
    build:
      context: ./gateway-test-gui
      dockerfile: Dockerfile
    container_name: gatewaytestfrontend
    ports:
      - "3000:3000"
    networks:
      apisix_network:

networks:
  apisix_network:
    driver: bridge
